version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing serverless
      - npm install -g serverless
      - npm install

  build:
    commands:
      - echo Building TypeScript
      - npm run build
      - echo Deploying with Serverless
      - serverless deploy --stage $ENVIRONMENT --region $REGION --conceal --verbose
