# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: personalproject11
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-tut-deploy

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
