service: serverless-tut-deploy

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: dist/handler.handler # 👈 compiled output path
    events:
      - httpApi: "*"
package:
  exclude:
    - handler.ts
    - tsconfig.json
    - buildspec.yml
    - node_modules/**
  include:
    - dist/**
