service: serverless-tut-deploy

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: dist/handler.handler # 👈 compiled output path
    events:
      - httpApi: "*"
plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    exclude: []
    target: node20
    platform: node
    concurrency: 10
